### ISSUE TITLE
Deploy continuo (homologação)

### ISSUE THREAD

**Issue by gabibguedes** [fga-eps-mds/2020-2-SiGeD#149]
## Descrição da issue

Criar o pipeline de deploy continuo do sistema de homologação de todos os serviços

## Nessa issue deve ser feito:

- Definir a hospedagem do sistema de homologação
- Criar action para o deploy continuo de homologação em todos os repositórios
- O deploy deve ser feito a cada commit da branch development

**Comment by vitorl-s** [comment]
Deploy continuo finalizado
