### ISSUE TITLE
Limitação de visualização de demandas por setor do usuário

### ISSUE THREAD

**Issue by gabibguedes** [fga-eps-mds/2020-2-SiGeD#160]
## História:

Eu, como administrador, desejo limitar a visualização de demandas por setor e usuário, a fim de que o usuário de um setor específico só veja as demandas do seu setor.

## Nessa issue deve ser feito:

- Restringir tela de demandas para, caso o usuário não seja admin, mostre somente as demandas do setor do usuário
- Restringir visualização de uma demanda específica para somente usuários do setor da demanda

## Critérios de aceitação:

- Usuários não admin não conseguem visualizar demandas de outros setores
- Lista de demandas filtrada pelo setor do usuário

**Comment by vitorl-s** [comment]
Não é mais necessária de acordo com o cliente
