### ISSUE TITLE
Filtro no prontuário

### ISSUE THREAD

**Issue by EzequielDeOliveira** [fga-eps-mds/2020-2-SiGeD#191]
## História:
Eu, como ---- , desejo visualizar ---  , a fim de ---

## Nessa issue deve ser feito:

- Descrever o que deve ser feito na issue em steps

## Critérios de aceitação:

- Filtro por status de demanda
- Filtro por categoria com dropdown autocomplete
- Filtro por ano e geral

**Comment by vitorl-s** [comment]
Issue já criada
