### ISSUE TITLE
Protótipo telas da sprint 4

### ISSUE THREAD

**Issue by GabrielOak** [fga-eps-mds/2020-2-SiGeD#68]
## Nessa issue deve ser feito:

- Criar tela de cadastrar cliente
- Criar tela de visualizar uma lista de clientes
- Criar tela de atualizar dados dos clientes
- Criar tela visualizar um único cliente
- Criar tela de cadastrar categorias
- Criar tela de visualizar uma lista de categorias
- Criar tela de atualizar as categorias

**Comment by vitorl-s** [comment]
Protótipo da sprint feito
