### ISSUE TITLE
Dojo de React

### ISSUE THREAD

**Issue by vitorl-s** [fga-eps-mds/2020-2-SiGeD#8]
## Descrição da issue

- Realizar dojo de React para o time de MDS

## Tasks:

- [x] - Montar apresentação
- [x] - Realizar apresentação
- [x] - Tirar possíveis dúvidas

**Comment by vitorl-s** [comment]
Dojo Finalizado

**Comment by yukioz** [comment]
Dojo completo e muito informativo.
