### ISSUE TITLE
Dojo de Teste

### ISSUE THREAD

**Issue by gabibguedes** [fga-eps-mds/2020-2-SiGeD#90]
## Descrição da issue

Será necessário que a equipe tenha conhecimento de testes para testar a aplicação.

## Nessa issue deve ser feito:

- Estudar testes em JS
- Fazer o Dojo com os MDSs

**Comment by vitorl-s** [comment]
Repriorizado para a sprint 6

**Comment by GabrielOak** [comment]
Dojo realizado!
