### ISSUE TITLE
Dojo de Context

### ISSUE THREAD

**Issue by EzequielDeOliveira** [fga-eps-mds/2020-2-SiGeD#91]
## Descrição da issue

- Essa issue tem o propósito de elamborar um dojo sobre a Context Api, que é a API do React js para compartilhamento de informações
## Nessa issue deve ser feito:

- Estudo sobre a Context API
- Elaborar e aplicar o Dojo para a equipe de MDS

**Comment by vitorl-s** [comment]
Repriorizado para a sprint 6

**Comment by vitorl-s** [comment]
Dojo Realizdo
